[theme]
base = "light"
primaryColor = "#6D28D9"
backgroundColor = "#FAF9FF"
secondaryBackgroundColor = "#F0ECFF"
textColor = "#282343"
font = "sans serif"

[server]
maxUploadSize = 50
headless = true

[browser]
gatherUsageStats = false
